@id=7ba33a59-f73c-4a42-af2c-c9a9b5580677

PUT http://localhost:5150/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine 2222",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}